### ISSUE TITLE
Implement score history in updateUI()

### ISSUE THREAD

**Issue by vkWeb** [perezvon/fcc-dice-game#4]

**Comment by vkWeb** [comment]
@perezvon I have assigned this to you, feel free to tackle when you get time :)

**Comment by shynonagons** [comment]
Wow can't believe it's been over 2 weeks! Finally got a chance to get to this --> #8

**Comment by vkWeb** [comment]
@perezvon Yes, it's been too long. My university tests are over so I can work this weekend. I'll try to complete some of the tasks assigned to me.
